#ifndef __CASSANDRA_CONFIG_HPP_INCLUDED__
#define __CASSANDRA_CONFIG_HPP_INCLUDED__

#define HAVE_OPENSSL
/* #undef HAVE_STD_ATOMIC */
/* #undef HAVE_BOOST_ATOMIC */
/* #undef HAVE_NOSIGPIPE */
#define HAVE_SIGTIMEDWAIT

#endif
